apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api-service
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: api-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-deployment
    spec:
      containers:
      - name: api
        image: imageholder
        ports:
        - containerPort: 5000